### ISSUE TITLE
Option to use 'textwidth'

### ISSUE THREAD

**Issue by fvictorio** [jrudess/vim-foldtext#1]
Hi, thanks for this plugin, it's really good!

I was wondering if you'd consider adding an option to use the value of `textwidth` instead of the width of the window. That way, if you are using the terminal in fullscreen, the number of folded lines is not too far away.

For example, right now:

![image](https://user-images.githubusercontent.com/417134/69806865-a8b54100-11c2-11ea-88cf-b435c0b1fc94.png)

With this change and a `textwidth` of 100:

![image](https://user-images.githubusercontent.com/417134/69806919-caaec380-11c2-11ea-8a7b-1f8e9a1fe84d.png)

As far as I can tell, the change would be adding something like this:

```viml
    if g:FoldText_use_textwidth && &textwidth > 0 && &textwidth <= width
      let width = &textwidth
    endif
```

I can make a PR if this is something you'd be willing to include.

Thanks again!

**Comment by jrudess** [comment]
Good idea.  To enable use:
```
let g:FoldText_width = 80
```
Where 80 is the starting  column for the fold information.

**Comment by fvictorio** [comment]
Thanks!
